---
serviceAccount:
  name: "vault"

nameOverride: ""

# Needed for install/maintenance jobs
kubectl:
  image:
    repository: bitnami/kubectl
    tag: 1.24
    pullPolicy: IfNotPresent

allowedAuthNamespaces:
  - namespace: services
    serviceaccount: "*"
    ttl: 72h
  # - namespace: cert-manager
  #   serviceaccount: "*"
  #   ttl: 72h
vault:
  ui: true
  image: vault:1.6.2

raft:
  performance_multiplier: 5
  pvc:
    accessMode: "ReadWriteOnce"
    storage: 2Gi

pki:
  customCA:
    # Set enabled to true and set other fields accordingly
    # to enable vault to mount a PKI engine and serve the
    # supplied CA.
    #
    # Note that all of the certificate/key material provided
    # must be PEM encoded. The ca_bundle.crt must only contain
    # certificates that comprise the trust chain, and it is important
    # that it does to ensure clients within the system can properly
    # verify issued certificates.
    #
    # These settings should be managed by system-level customization, versus
    # directly in chart.
    #
    enabled: true
    secret: platform-ca-secret
    private_key: tls.key
    certificate: tls.crt
    ca_bundle: ca.crt
ssh:
  certs:
    # Set enabled to true and uncomment/edit/add realms to
    # configure SSH Certificate trust realms.
    # For each realm, allowedAuthNamespaces control
    # the allow-list of service accounts accepted by namespace,
    # for K8S auth to vault.
    #
    # Note that that SSH CA support is currently limited to
    # user key support. Host key signing is also supported via
    # vault, but not enabled here.
    #
    enabled: true
    realms:
      - name: compute
        allowedAuthNamespaces:
          - services
