---
apiVersion: v2
# appVersion: 0.2.2
# description: 
name: keycloak
type: application
version: 0.1.0
sources:
- https://github.com/bitnami/charts/tree/master/bitnami/keycloak
dependencies:
- name: cray-service
  version: 8.0.3
  repository: https://nowireless.github.io/base-charts
- name: keycloak
  version: 9.3.6
  repository: https://charts.bitnami.com/bitnami