{
 "title": "Hue exporter",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "hue_sensor_value{type=\"ZLLTemperature\"} / 100",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Rooms",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "hue_group_on{type=\"Room\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Light level",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Lux" }
   ],
   "targets": [
    {
     "expr": "hue_sensor_value{type=\"ZLLLightLevel\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Battery levels",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "min(hue_sensor_battery{type=~\"(ZLLPresence|ZLLSwitch)\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}