#
# The Following should move into the external-dns super chart
#
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: external-dns-etcd-client-cert
  namespace: external-dns
spec:
  commonName: external-dns-etcd-client-cert
  dnsNames:
    - "external-dns-etcd" # Endpoint for in the same namespace
    - "*.external-dns-etcd.external-dns.svc.cluster.local" 
    - "*.external-dns-etcd-headless.external-dns.svc"
    - "*.external-dns-etcd-headless.external-dns.svc.cluster.local"
    - localhost
    - ""
  ipAddresses:
    - 127.0.0.1
  secretName: external-dns-etcd-client-cert
  usages:
    - server auth
    - client auth
  issuerRef:
    name: "{{ .Values.tls.issuer }}"
    kind: Issuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: external-dns-etcd-peer-cert
  namespace: external-dns
spec:
  commonName: external-dns-etcd-peer-cert
  dnsNames:
    - "*.external-dns-etcd.external-dns.svc.cluster.local" 
    - "*.external-dns-etcd-headless.external-dns.svc"
    - "*.external-dns-etcd-headless.external-dns.svc.cluster.local"
    - localhost
    - ""
  ipAddresses:
    - 127.0.0.1
  secretName: external-dns-etcd-peer-cert
  usages:
    - server auth
    - client auth
  issuerRef:
    name: "{{ .Values.tls.issuer }}"
    kind: Issuer
