
# Keeping this for posterity as an example to populate vault 

{{/*
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: external-dns-etcd-generate-root-password
#   annotations:
#     helm.sh/hook: pre-install
#     helm.sh/hook-weight: "-10"
#     helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
# ---
# apiVersion: v1
# kind: Secret
# type: kubernetes.io/service-account-token
# metadata:
#   name: external-dns-etcd-generate-root-password-token
#   annotations:
#     helm.sh/hook: pre-install
#     helm.sh/hook-weight: "-9"
#     helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
#     kubernetes.io/service-account.name: external-dns-etcd-generate-root-password
# ---
# # TODO replace this with a call to vault to create a password, instead of helm:
# # https://banzaicloud.com/docs/bank-vaults/mutating-webhook/configuration/#write-a-value-into-vault
# # https://github.com/sethvargo/vault-secrets-gen
# apiVersion: v1
# kind: Secret
# metadata:
#   name: external-dns-etcd-root-password
#   annotations:
#     helm.sh/hook: pre-install
#     helm.sh/hook-weight: "-8"
#     helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
# type: Opaque
# data:
#   # generate 32 chars long random string, base64 encode it and then double-quote the result string.
#   password: {{ randAlphaNum 32 | b64enc | quote }}
# ---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: external-dns-etcd-generate-root-password
#   labels:
#     app.kubernetes.io/managed-by: {{ .Release.Service }}
#   annotations:
#     helm.sh/hook: pre-install
#     helm.sh/hook-weight: "-0"
#     helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
# spec:
#   template:
#     metadata:
#       name: generate-root-password
#       labels:
#         app.kubernetes.io/managed-by: {{ .Release.Service }}
#       annotations:
#         sidecar.istio.io/inject: "false"
#     spec:
#       restartPolicy: Never
#       serviceAccountName: external-dns-etcd-generate-root-password
#       containers:
#         - name: generate
#           image: {{ .Values.vault.image.repository }}:{{ .Values.vault.image.tag }}
#           imagePullPolicy: {{ .Values.vault.image.pullPolicy }}
#           env:
#           - name: VAULT_ADDR
#             value: http://vault.vault.svc.cluster.local:8200
#           - name: ROOT_PASSWORD
#             valueFrom:
#               secretKeyRef:
#                 name: external-dns-etcd-root-password
#                 key: password
#                 optional: false
#           command:
#             - /bin/sh
#             - -c
#             - |
#               export VAULT_TOKEN=$(vault write auth/kubernetes/login role=external-dns jwt="$(cat /run/secrets/kubernetes.io/serviceaccount/token)"  | grep "^token " | awk '{print $2}')
#               vault kv put secret/external-dns-etcd/creds "password=$ROOT_PASSWORD"
 */}}