# Default values for hack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The following is for the webhook job
# vault:
#   image:
#     repository: vault
#     tag: 1.6.2
#     pullPolicy: IfNotPresent

tls:
  issuer: cert-manager-issuer-common

etcd:
  # global:
  #   storageClass: csi-rbd-sc-fast
  persistence:
    enabled: true

  replicaCount: 3

  # extraEnvVars:
  # - name: BITNAMI_DEBUG
  #   value: "true"
  ## Vault secrets webhook example
  # - name: FOOBAR
  #   value: vault:secret/external-dns-etcd/creds#password
  # podAnnotations:
  #   vault.security.banzaicloud.io/vault-addr: http://vault.vault.svc.cluster.local:8200
  #   vault.security.banzaicloud.io/vault-role: external-dns

  serviceAccount:
    create: true
    name: external-dns-etcd
    automountServiceAccountToken: true

  auth:
    rbac:
      enabled: false
      create: false
    client:
      secureTransport: true
      enableAuthentication: true
      existingSecret: external-dns-etcd-client-cert
      certFilename: tls.crt
      certKeyFilename: tls.key
      caFilename: ca.crt
    peer:
      secureTransport: true
      enableAuthentication: true
      existingSecret: external-dns-etcd-peer-cert
      certFilename: tls.crt
      certKeyFilename: tls.key
      caFilename: ca.crt