{
 "title": "RGW Sync Overview",
 "tags": [
  "ceph",
  "overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "rgw_servers", "query": "prometheus" },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Replication (throughput) from Source Zone",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (source_zone) (rate(ceph_data_sync_from_zone_fetch_bytes_sum[30s]))",
     "legendFormat": "{{source_zone}}"
    }
   ]
  },
  {
   "title": "Replication (objects) from Source Zone",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7.4, "x": 8.3, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Objects/s" }
   ],
   "targets": [
    {
     "expr": "sum by (source_zone) (rate(ceph_data_sync_from_zone_fetch_bytes_count[30s]))",
     "legendFormat": "{{source_zone}}"
    }
   ]
  },
  {
   "title": "Polling Request Latency from Source Zone",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (source_zone) (rate(ceph_data_sync_from_zone_poll_latency_sum[30s]) * 1000)",
     "legendFormat": "{{source_zone}}"
    }
   ]
  },
  {
   "title": "Unsuccessful Object Replications from Source Zone",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Count/s" }
   ],
   "targets": [
    {
     "expr": "sum by (source_zone) (rate(ceph_data_sync_from_zone_fetch_errors[30s]))",
     "legendFormat": "{{source_zone}}"
    }
   ]
  }
 ]
}